version: "3.9"
services:
  soap-service-web:
    build: .
    ports:
      - 8000:8000
    hostname: tubes-soap-service
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - soap-service-db
  soap-service-db:
    image: mysql:latest
    ports:
      - 3309:3306
    env_file: .env
    hostname: tubes-soap-db
volumes:
  db:
    driver: local
